JuliaIO/PNGFiles.jl

- Project.toml
- src/io.jl
- src/wraphelpers.jl
- test/runtests.jl
Port of https://github.com/ianshmean/ImageIO.jl/pull/3 where I also describe what is going on.
This _should_ work with https://github.com/JuliaIO/FileIO.jl/pull/257, at least locally it seems to work fine. I'd certainly welcome some code review here:)
I ran the benchmarks from https://github.com/JuliaIO/PNG.jl/issues/1, but I'm not sure how make FileIO actually use QuartzImageIO (guess it's only used on Mac?), so here are my local results:
```
[ Info: Testing with rand(RGB{N0f8}, 244, 244) image -----------------------------
[ Info: Testing FileIO with ImageMagick (dedicated environment, new instance)
Time to first save (including save): 2.2 seconds
Save @btime:  23.942 ms (1424 allocations: 597.88 KiB)
Load @btime:  4.331 ms (1584 allocations: 605.14 KiB)
[ Info: Testing FileIO with PNG …
```
> Png tweaks

- Project.toml
- README.md
- src/io.jl
- test/runtests.jl
The need to use the FileIO entry methods seemed OTT when you know you're working with PNG's and wanted to use PNGFiles directly, so I just added methods for string file paths and switched over the tests to use those entry points (remove the FileIO dep from tests for now)
> Allow string paths for load and save

- Project.toml
- src/PNGFiles.jl
- src/io.jl
- test/runtests.jl
I've set up https://github.com/JuliaIO/ImageIO.jl as a lazy-loader for PNGFiles and the future JPEGFiles, TIFFFiles etc.
It handles the *Files deps, so that a user would just need to install ImageIO, and we can add format support to ImageIO without requiring the user to install each new format package.
The additional time in loading & saving images with the ImageIO layer should be on the order of a few ns, so negligible
@Drvi If you're ok with this, I can merge into #5 given it's become more of a final polishing PR
> Remove FileIO API, move to ImageIO for FileIO integration 

- Project.toml
- src/PNGFiles.jl
- src/io.jl
- src/utils.jl
- test/runtests.jl
- test/test_invalid_inputs.jl
- test/test_paletted_images.jl
- test/test_pngsuite.jl
- test/test_synthetic_images.jl
- test/test_testimages.jl
- test/utils.jl
Allows saving of files using palette table
Example usage below:
```
using PNGFiles, Images
nclasses = 15
myArray = [UInt8.(mod(x+y, nclasses)) for x=1:640, y=1:480 ]
PNGFiles.save("myfile_pal.png", myArray, palette=colortable)
```
> Initial attempt to add palette support

- src/PNGFiles.jl
- src/io.jl
- src/wraphelpers.jl
Candidate fix for #15 (which may be more than "thread safety" as the title suggests)
> Generate cfunctions png_error_fn and png_warn_fn at runtime

- src/io.jl
Quoting [Wikipedia](https://en.wikipedia.org/wiki/Portable_Network_Graphics), "The motivation for creating the PNG format was the realization, in early 1995, that the Lempel–Ziv–Welch (LZW) data compression algorithm used in the Graphics Interchange Format (GIF) format was patented by Unisys. "  Therefore, defaulting saving PNG-files without compression goes a bit against the original motivation of the format. I propose setting the default value for `compression_level` to `Z_BEST_SPEED` instead of `Z_NO_COMPRESSION`.
Makie has adopted ImageIO, but this caused a regression in the size of the saved files https://github.com/JuliaPlots/Makie.jl/issues/629.
> Default to Z_BEST_SPEED instead of Z_NO_COMPRESSION

- src/io.jl
For CI testing. Supersedes #17 
cc. @jaakkor2
> Default to Z_BEST_SPEED instead of Z_NO_COMPRESSION (v2)

- .gitignore
- src/io.jl
....since not all IOs have a lock field...
> use generic interface instead of accessing fields

- src/PNGFiles.jl
This takes a good fraction of a second to precompile, so it's worth doing.
Without it:
```julia
julia> using SnoopCompileCore, FileIO
julia> tinf = @snoopi tmin=0.005 load("/home/tim/src/vigra/src/examples/cameraman.png")
6-element Vector{Tuple{Float64,Core.MethodInstance}}:
(0.00689387321472168, MethodInstance for setindex!(::Dict{Pkg.BinaryPlatforms.Platform,Dict{String,Any}}, ::Dict{String,Any}, ::Pkg.BinaryPlatforms.FreeBSD))
(0.007667064666748047, MethodInstance for permutedims(::Matrix{ColorTypes.Gray{FixedPointNumbers.N0f8}}, ::Tuple{Int64,Int64}))
(0.013384103775024414, MethodInstance for collect(::Base.Generator{Base.Generator{Base.OneTo{Int64},Base.var"#183#184"{Matrix{ColorTypes.Gray{FixedPointNumbers.N0f8}}}},typeof(pointer)}))
(0.020144939422607422, MethodInstance for …
```
> Precompile load(::String)

- Project.toml
- src/io.jl
- test/test_paletted_images.jl
- test/test_pngsuite.jl
- test/utils.jl
As seen in #25, the conversion of colortype arrays has changed behavior and was causing both warnings and failures
@Drvi does this look right to you?
We probably want to merge this before #25 and rebase that
> Fix for changed colortype conversion behavior

- src/PNGFiles.jl
- src/io.jl
This PR adds support for loading directly from an `IOBuffer`. This was previously possible to do by using `FileIO.load`. I'm not sure how that was done but this PR seems to significantly reduce the time of that as well.
Someone who is experienced with the `unsafe` Julia functions should review that they are used in a sound way.
> Support loading from IOBuffer.

- Project.toml
- gen/libpng/libpng_api.jl
- src/PNGFiles.jl
- src/io.jl
- test/runtests.jl
- test/test_io.jl
This is an attempt to address #22. The `save` specifies the destination must be `::IO`, which are all supposed to implement  `unsafe_write`, so use that instead of asking for the file handle. This allows writing to `IOBuffer`, but `Base64EncodePipe` still needs a release of Julia with JuliaLang/Julia#37520. The corresponding test is marked broken for now.
> Save to iobuffer

- src/io.jl
This "fixes" the error that Pluto raises (with ImageIO only) when trying to display an image, e.g., `img = rand(RGB{N0f8}, 4, 4)`:
```julia
From worker 2:	Errors encountered while saving nothing.
From worker 2:	All errors:
From worker 2:	===========================================
From worker 2:	MethodError: no method matching lock(::PNGFiles.var"#13#14"{Int64, Int64, Int64, Nothing, IOContext{IOBuffer}, Matrix{ColorTypes.RGB{FixedPointNumbers.N0f8}}, Ptr{Nothing}, Ptr{Nothing}}, ::IOContext{IOBuffer})
From worker 2:	Closest candidates are:
From worker 2:	  lock(::Any, !Matched::Base.GenericCondition) at condition.jl:78
From worker 2:	  lock(::Any, !Matched::Base.AbstractLock) at lock.jl:184
From worker 2:	  lock(::Any, !Matched::WeakKeyDict) at weakkeydict.jl:76
From worker 2: …
```
> bypass lock for IOContext

- Project.toml
- src/io.jl
- test/test_synthetic_images.jl
Fixes https://github.com/JuliaIO/FileIO.jl/issues/352
> Support ARGB32 images

- gen/libpng/libpng_api.jl
- gen/libpng/prologue.jl
- src/io.jl
- some simplifications reading `PNG_INFO_...` flags, avoids further `png_get_valid` calls.
- add a message saying that `libpng_api.jl` is auto-generated
- added checks on `valid_bKGD` and `valid_PLTE`
- simplify `png_set_gamma` logic (strictly equivalent)
- more debugging info when `JULIA_DEBUG=PNGFiles` is set
> Simplifications, more debug

- Project.toml
- src/io.jl
- src/utils.jl
- test/test_images/synth_images.jl
This just adds two missing methods, loading the image back is still `Gray{N0f8}` as 1bit encoding is not yet supported.
> support Gray{Bool} array

- .github/workflows/benchmark.yml
It's sometimes unnecessary to run the comprehensive benchmark test.
> only run benchmark on 'run benchmark' label

- src/io.jl
The palette is an output parameter, so this was corrupting the Array structure. It would sort of accidentally always work before, but this is much better.
> fix memory corruption when reading palette

- .github/workflows/test.yml
- test/runtests.jl
Update: Ready to go now the new cache has been released
~Please feel free to unsubscribe. This is a demo~
> Add `julia-actions/cache` with revamped depot caching 

- src/io.jl
Fixes https://github.com/JuliaIO/PNGFiles.jl/issues/74
try fix
```
TypeError: in RefArray, in A, expected A<:(AbstractArray{Ptr{UInt8}}), got Type{Vector{Ptr{RGBA{N0f16}}}}
Stacktrace:
[1] Ref{Ptr{UInt8}}(a::Vector{Ptr{RGBA{N0f16}}})
@ Base ./refpointer.jl:158
[2] cconvert(::Type{Ptr{Ptr{UInt8}}}, a::Vector{Ptr{RGBA{N0f16}}})
@ Base ./refpointer.jl:176
[3] png_read_image(png_ptr::Ptr{Nothing}, image::Vector{Ptr{RGBA{N0f16}}})
@ PNGFiles ~/work/PNGFiles.jl/PNGFiles.jl/gen/libpng/libpng_api.jl:558
[4] _load!(buffer::Matrix{RGBA{N0f16}}, png_ptr::Ptr{Nothing}, info_ptr::Ptr{Nothing})
@ PNGFiles ~/work/PNGFiles.jl/PNGFiles.jl/src/io.jl:256
[5] #invokelatest#2
@ ./essentials.jl:950 [inlined]
[6] invokelatest
@ ./essentials.jl:947 [inlined]
[7] _load(png_ptr::Ptr{Nothing}, …
```
> Fix RefArray issue on julia nightly

- src/io.jl
- test/runtests.jl
- test/test_dpi.jl
I would like to make Makie write `dpi` information into the pngs it produces. This PR adds the necessary ability to PNGFiles.
> Add ability to write pixel density into pngs
